default:
  image: node:17
  before_script:
    - npm i -g @nestjs/cli

stages:
  - build
  - release

build:
  stage: build
  script:
    - make build

release:
  stage: release
  script:
    - make release